"""Add liberation journey tables

Revision ID: 08012d02811d
Revises: 3ca19a5a7701
Create Date: 2026-04-19 01:38:09.733839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08012d02811d'
down_revision: Union[str, Sequence[str], None] = '3ca19a5a7701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journey_code', sa.String(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='journeystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_journeys_journey_code'), 'user_journeys', ['journey_code'], unique=False)
    op.create_index(op.f('ix_user_journeys_user_id'), 'user_journeys', ['user_id'], unique=False)
    op.create_table('user_journey_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_theme', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('locked', 'available', 'completed', name='stepstatus'), nullable=False),
    sa.Column('morning_feeling', sa.Text(), nullable=True),
    sa.Column('ai_greeting', sa.Text(), nullable=True),
    sa.Column('ai_exercise_text', sa.Text(), nullable=True),
    sa.Column('ai_why_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('energy_level_after', sa.Integer(), nullable=True),
    sa.Column('reflection_opened', sa.Text(), nullable=True),
    sa.Column('reflection_takeaway', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['user_journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_journey_steps_journey_id'), 'user_journey_steps', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_journey_steps_journey_id'), table_name='user_journey_steps')
    op.drop_table('user_journey_steps')
    op.drop_index(op.f('ix_user_journeys_user_id'), table_name='user_journeys')
    op.drop_index(op.f('ix_user_journeys_journey_code'), table_name='user_journeys')
    op.drop_table('user_journeys')
    # ### end Alembic commands ###
