"""add is_profile_setup to user

Revision ID: 2260ebd3a9d5
Revises: 53c747c60329
Create Date: 2026-05-20 23:15:27.308305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2260ebd3a9d5'
down_revision: Union[str, Sequence[str], None] = '53c747c60329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_profile_setup', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_setup')
    # ### end Alembic commands ###
