"""update story model to match figma fields

Revision ID: 3e1428ef72b7
Revises: e898c509cede
Create Date: 2026-05-13 04:28:47.960751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e1428ef72b7'
down_revision: Union[str, Sequence[str], None] = 'e898c509cede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('story_input', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('growth_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('stories', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('stories', 'emotional_context')
    op.drop_column('stories', 'deepest_desire_fear')
    op.drop_column('stories', 'country_city')
    op.drop_column('stories', 'specific_trigger')
    op.drop_column('stories', 'relationship_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('relationship_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('specific_trigger', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('country_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('deepest_desire_fear', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('emotional_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('stories', 'tags')
    op.drop_column('stories', 'growth_areas')
    op.drop_column('stories', 'story_input')
    op.drop_column('stories', 'first_name')
    # ### end Alembic commands ###
