"""Initial schema

Revision ID: 4086cbb312e8
Revises: 
Create Date: 2026-04-18 23:56:27.560016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4086cbb312e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_credits_remaining', sa.Integer(), nullable=False),
    sa.Column('max_daily_credits', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    op.create_table('story_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('touch_score', sa.Float(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('resonance_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_id', name='uq_story_user_feedback')
    )
    op.create_index(op.f('ix_story_feedback_story_id'), 'story_feedback', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_feedback_user_id'), 'story_feedback', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('height', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('slider_sexuality_life_energy', sa.Integer(), nullable=True))
    op.drop_column('user_profiles', 'region')
    op.drop_column('user_profiles', 'slider_social_relational')
    op.drop_column('user_profiles', 'slider_security_energy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('slider_security_energy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('slider_social_relational', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'slider_sexuality_life_energy')
    op.drop_column('user_profiles', 'height')
    op.drop_index(op.f('ix_story_feedback_user_id'), table_name='story_feedback')
    op.drop_index(op.f('ix_story_feedback_story_id'), table_name='story_feedback')
    op.drop_table('story_feedback')
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_table('user_credits')
    # ### end Alembic commands ###
