"""Add job tracking to LiberationDefinition

Revision ID: 497daa8c7544
Revises: 947dc7baf269
Create Date: 2026-05-12 03:51:41.042631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497daa8c7544'
down_revision: Union[str, Sequence[str], None] = '947dc7baf269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    generationstatus_liberation = sa.Enum('processing', 'completed', 'failed', name='generationstatus_liberation')
    generationstatus_liberation.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liberation_definitions', sa.Column('job_id', sa.String(), nullable=True))
    op.add_column('liberation_definitions', sa.Column('generation_status', generationstatus_liberation, nullable=True))
    op.create_index(op.f('ix_liberation_definitions_job_id'), 'liberation_definitions', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liberation_definitions_job_id'), table_name='liberation_definitions')
    op.drop_column('liberation_definitions', 'generation_status')
    op.drop_column('liberation_definitions', 'job_id')
    # ### end Alembic commands ###
    
    generationstatus_liberation = sa.Enum('processing', 'completed', 'failed', name='generationstatus_liberation')
    generationstatus_liberation.drop(op.get_bind(), checkfirst=True)
