"""added google auth fields

Revision ID: 8427782400d1
Revises: 08012d02811d
Create Date: 2026-04-20 06:04:47.628263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8427782400d1'
down_revision: Union[str, Sequence[str], None] = '08012d02811d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liberation_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.Enum('pending', 'approved', 'rejected', name='definitionstatus'), nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liberation_definitions_created_by'), 'liberation_definitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_liberation_definitions_journey_code'), 'liberation_definitions', ['journey_code'], unique=True)
    op.create_table('liberation_day_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_theme', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['liberation_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liberation_day_definitions_definition_id'), 'liberation_day_definitions', ['definition_id'], unique=False)
    op.drop_column('user_journey_steps', 'audio_url')
    op.add_column('user_journeys', sa.Column('definition_id', sa.UUID(), nullable=True))
    op.add_column('user_journeys', sa.Column('reminder_preference', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_journeys_definition_id'), 'user_journeys', ['definition_id'], unique=False)
    op.create_foreign_key(None, 'user_journeys', 'liberation_definitions', ['definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_journeys', type_='foreignkey')
    op.drop_index(op.f('ix_user_journeys_definition_id'), table_name='user_journeys')
    op.drop_column('user_journeys', 'reminder_preference')
    op.drop_column('user_journeys', 'definition_id')
    op.add_column('user_journey_steps', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_liberation_day_definitions_definition_id'), table_name='liberation_day_definitions')
    op.drop_table('liberation_day_definitions')
    op.drop_index(op.f('ix_liberation_definitions_journey_code'), table_name='liberation_definitions')
    op.drop_index(op.f('ix_liberation_definitions_created_by'), table_name='liberation_definitions')
    op.drop_table('liberation_definitions')
    # ### end Alembic commands ###
