"""add figma alignment fields to liberation journey

Revision ID: 85ed9744a9c3
Revises: b3c4d5e6f7a8
Create Date: 2026-05-13 23:10:47.735132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ed9744a9c3'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liberation_definitions', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('liberation_definitions', sa.Column('what_to_expect', sa.JSON(), nullable=True))
    op.add_column('liberation_definitions', sa.Column('setup_instructions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liberation_definitions', 'setup_instructions')
    op.drop_column('liberation_definitions', 'what_to_expect')
    op.drop_column('liberation_definitions', 'rating')
    # ### end Alembic commands ###
