"""Add exercise and why text to liberation day definition

Revision ID: ae7b2e4eacfd
Revises: c263db9d3094
Create Date: 2026-05-13 19:28:54.345360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7b2e4eacfd'
down_revision: Union[str, Sequence[str], None] = 'c263db9d3094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liberation_day_definitions', sa.Column('exercise_text', sa.Text(), nullable=True))
    op.add_column('liberation_day_definitions', sa.Column('why_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liberation_day_definitions', 'why_text')
    op.drop_column('liberation_day_definitions', 'exercise_text')
    # ### end Alembic commands ###
